#!/usr/bin/env node
// scripts/module_map.mjs — STAMP AN IMPORT MAP INTO index.html SO THE ENGINE IS VERSIONED WITH THE APP.
//
// ⛔ WHY THIS EXISTS, AND I WATCHED IT HAPPEN: `index.html` cache-busts `app.js?v=1.9.470` and `style.css`, but app.js imports 107
// engine modules by plain relative path — and every module an engine module imports is plain too. So a browser can fetch a NEW
// app.js and serve OLD engine modules out of its cache. Verifying v1.9.470 in the browser, the page ran the new app.js against a
// cached `quests.js` and died with *"The requested module './quests.js' does not provide an export named 'creditQuestGiver'"*.
// ⚠️ THE SILENT CASE IS WORSE THAN THE THROW: a stale module that still has every export just behaves like last release, which is
// indistinguishable from a bug in the new one. index.html's own boot-watchdog comment records a real GitHub Pages module failure,
// so this surface has bitten the game in production before.
//
// ⛑ AN IMPORT MAP FIXES IT AT ONE PLACE. Keys resolve against the document and specifiers against their referrer, and the two are
// compared as URLs — so a single key `./engine/melee.js` catches BOTH app.js's `./engine/melee.js` and carriage.js's `./melee.js`.
// One entry per module, regenerated from the version app.js declares, and the map must precede the first module script.
//
// `--check` verifies without writing (the same contract as certify_counts.mjs, engine_map.mjs and interface_counts.mjs).
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const rd = (p) => readFileSync(ROOT + p, "utf8");
const check = process.argv.includes("--check");

// ⛔ THE VERSION IS DECLARED IN ONE PLACE and everything else is stamped from it — app.js used to hold it as a const, which put it
// out of reach of `state.js` (the content loader) and of this generator.
const ver = (rd("engine/version.js").match(/export const APP_VERSION = "([^"]+)"/) || [])[1];
if (!ver) { console.error("  FAIL  module_map: engine/version.js declares no APP_VERSION"); process.exit(2); }
// ⛔ app.js KEEPS A GATED COPY, because six readers take the version from its const — bump_version, wiring_audit, apparatus_inject,
// certify_counts and four doc checks. ⚠️ A copy is only honest while something fails when it drifts, which is this line.
const appVer = (rd("app.js").match(/const APP_VERSION = "([^"]+)"/) || [])[1];
if (appVer !== ver) {
  console.error(`  FAIL  module_map: app.js says v${appVer} and engine/version.js says v${ver} — one build cannot have two versions. Bump engine/version.js and run scripts/bump_version.mjs --set ${ver}.`);
  process.exit(1);
}

// Every module the graph can reach: engine/*.js, plus the one dynamic import outside it.
const mods = readdirSync(ROOT + "engine").filter(f => /\.(js|mjs)$/.test(f)).sort().map(f => `./engine/${f}`);
const extra = ["./scripts/world/terrain.mjs"].filter(p => existsSync(ROOT + p.slice(2)));
const all = [...mods, ...extra];

const OPEN = "  <!-- module-map: generated by scripts/module_map.mjs — the engine is versioned with the app, or a browser serves a new app.js against cached modules -->";
const CLOSE = "  <!-- /module-map -->";
const body = JSON.stringify({ imports: Object.fromEntries(all.map(p => [p, `${p}?v=${ver}`])) }, null, 1)
  .split("\n").map(l => "    " + l).join("\n");
const block = `${OPEN}\n  <script type="importmap">\n${body}\n  </script>\n${CLOSE}`;

const html = rd("index.html");
const eol = html.includes("\r\n") ? "\r\n" : "\n";
// ⛔ AND THE TWO STAMPS IT ALREADY CARRIED. They were hand-patched every ship beside a hand-patched const, which is three copies of
// one number kept in step by hand — the staleness generator Aevi ruled on for a stored count, in the place where drift means a
// player runs half of one build and half of another.
const flat = html.replace(/\r\n/g, "\n")
  .replace(/href="style\.css\?v=[^"]*"/, `href="style.css?v=${ver}"`)
  .replace(/src="app\.js\?v=[^"]*"/, `src="app.js?v=${ver}"`);
const has = flat.includes(OPEN) && flat.includes(CLOSE);
const next = has
  ? flat.replace(new RegExp(`${OPEN.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${CLOSE.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`), block)
  // ⛔ BEFORE THE FIRST MODULE SCRIPT, which is where an import map is allowed to be and nowhere else.
  : flat.replace(/(\n\s*<script type="module" src="app\.js)/, `\n${block}$1`);

if (next === flat) { console.log(`  ok    module_map: ${all.length} modules pinned at v${ver}`); process.exit(0); }
if (!has && next === flat) { console.error("  FAIL  module_map: index.html has no module script to sit before"); process.exit(2); }
if (check) {
  const why = has ? `the map is stale (app.js is at v${ver})` : "index.html carries no module map at all";
  console.error(`  FAIL  module_map: ${why} — a browser can serve cached engine modules against a new app.js.`);
  process.exit(1);
}
writeFileSync(ROOT + "index.html", next.split("\n").join(eol));
console.log(`  stamped module_map: ${all.length} modules pinned at v${ver}`);
