// scripts/substrate_atlas.mjs — 39 REGIONS × 6 SOURCES, PRINTED ONCE, BECAUSE NOBODY HAS EVER SEEN IT.
//
// ⛔ ERIK: "Spec a review of the world power source distribution, as well as the skills and how each would
// perform in the world's distribution per region and area." ⚑ AEVI, SPEC_ground_card_everywhere §3: "39
// regions × 6 sources is a table nobody has ever printed… IT IS A DESIGN DECISION NOBODY HAS EVER SEEN THE
// NUMBERS FOR, AND IT SHOULD BE ERIK'S."
//
// ⚠️ EVERY FIGURE IS COMPUTED BY CALLING `bandFactor` — the production curve — never re-derived here. A
// second implementation of the curve is how the two would drift, and this document exists to be trusted.
//
// ⛑ AND THE ONE THING THE TABLE CORRECTS: precursor and nanite share a band, and Aevi's §3 reads that as
// "an identical band and THEREFORE an identical map… either the two-pairs cosmology working exactly as
// authored, or two sources doing one source's job." ⛔ Measured, the maps are almost entirely DIFFERENT:
// nanite reads `naniteField.byRegion`, not `substrateDensity`, and 37 of 39 regions carry a different value
// — the Deepwood is lattice 0.90 and nanite 0.08. The model's own provenance says it ("MIRRORING IS NOT
// MERGING") and the numbers agree. Same curve, different world.
//
// ⚠️ Same contract as roster.mjs: default prints a DIFF, `--write` applies, `--check` exits 1 if stale
// (the suite runs this), `--md` prints the generated block alone.
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadContentHeadless } from "../tests/headless_content.mjs";
import { bandFactor, bandFor } from "../engine/substrate.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const DOC = join(root, "docs/SUBSTRATE_ATLAS.md");
const BEGIN = "<!-- BEGIN substrate-atlas -->";
const END = "<!-- END substrate-atlas -->";
const WRITE = process.argv.includes("--write");
const CHECK = process.argv.includes("--check");
const MD = process.argv.includes("--md");

const C = await loadContentHeadless();
const sm = C.substrateModel || {};
const density = sm.substrateDensity || {};
const nanite = sm.naniteField?.byRegion || {};
const sources = sm.sourceBands?.sources || {};
const regionName = (id) => (C.regions || []).find((r) => (r.regionId || r.id) === id)?.name || id;

// ⛔ THE FIELD A SOURCE READS IS PART OF THE SOURCE. `field: "nanite"` routes to its own geography, and
// reading every source off `substrateDensity` is exactly the mistake this atlas is here to prevent.
const fieldValue = (srcName, src, regionId) => {
  if (src?.field === "nanite") {
    const v = Number(nanite[regionId]?.v);
    return Number.isFinite(v) ? v : null;
  }
  const v = Number(density[regionId]);
  return Number.isFinite(v) ? v : null;
};

const regionIds = Object.keys(density).sort((a, b) => Number(density[b]) - Number(density[a]));
const srcNames = Object.keys(sources);

// per source: where it works, where it starves
const perSource = srcNames.map((name) => {
  const src = sources[name];
  const band = src?.band || null;
  const rows = regionIds.map((rid) => {
    const v = fieldValue(name, src, rid);
    if (v == null) return null;
    // ⚑ THE PRODUCTION CURVE, CALLED. `band: null` + `floor: true` is `body` — never starved anywhere.
    const f = band ? bandFactor(band, v) : (src?.floor ? 1 : null);
    return { rid, v, f };
  }).filter(Boolean);
  const inside = band ? rows.filter((r) => r.v >= band.center - band.width && r.v <= band.center + band.width) : rows;
  const best = rows.slice().sort((a, b) => b.f - a.f)[0] || null;
  const worst = rows.slice().sort((a, b) => a.f - b.f)[0] || null;
  return { name, src, band, rows, inside, best, worst };
});

// which traditions ride which source, so "a tradition nobody can play well anywhere" is answerable
const traditionsBySource = {};
for (const t of Object.values(C.traditionIndex?.byId || {})) {
  const s = t?.powerSource || t?.source || null;
  if (!s) continue;
  (traditionsBySource[s] = traditionsBySource[s] || []).push(t.traditionId);
}

const pct = (x) => `${Math.round(x * 100)}%`;
const f2 = (x) => (x == null ? "—" : x.toFixed(2));

const out = [];
out.push(BEGIN);
out.push("");
out.push("**GENERATED by `scripts/substrate_atlas.mjs` — every factor is a call to `bandFactor`, the production curve, never a second implementation.** ⚠️ Regenerate with `node scripts/substrate_atlas.mjs --write`; never hand-edit inside the markers.");
out.push("");
out.push(`**${regionIds.length} regions · ${srcNames.length} sources · density ${f2(Math.min(...regionIds.map(r => Number(density[r]))))}–${f2(Math.max(...regionIds.map(r => Number(density[r]))))}, median ${f2([...regionIds.map(r => Number(density[r]))].sort((a, b) => a - b)[Math.floor(regionIds.length / 2)])}.**`);
out.push("");
out.push("## HOW MUCH OF THE WORLD EACH SOURCE CAN WORK IN");
out.push("");
out.push("| source | band | reads | regions INSIDE | best | worst |");
out.push("|---|---|---|---|---|---|");
for (const s of perSource) {
  const bandTxt = s.band ? `${f2(s.band.center - s.band.width)}–${f2(s.band.center + s.band.width)}` : "*floor, no band*";
  const readsTxt = s.src?.field === "nanite" ? "`naniteField`" : (s.band ? "`substrateDensity`" : "—");
  const insideTxt = s.band ? `**${s.inside.length} of ${s.rows.length}** — ${pct(s.inside.length / s.rows.length)}` : "**never starves**";
  // ⚠️ A FLOOR SOURCE HAS NO BEST OR WORST GROUND — `body` is 1.00 everywhere, so naming a region here
  // would invent a preference the mechanic does not have. "Never at a loss anywhere, but never peaks."
  const bestTxt = !s.band ? "*everywhere 1.00*" : (s.best ? `${regionName(s.best.rid)} ${f2(s.best.f)}` : "—");
  const worstTxt = !s.band ? "*nowhere below 1.00*" : (s.worst ? `${regionName(s.worst.rid)} ${f2(s.worst.f)}` : "—");
  out.push(`| **${s.name}** | ${bandTxt} | ${readsTxt} | ${insideTxt} | ${bestTxt} | ${worstTxt} |`);
}
out.push("");
out.push("⛔ **AND PRECURSOR AND NANITE DO NOT SHARE A MAP, THOUGH THEY SHARE A BAND.** `nanite` reads `naniteField.byRegion`; `precursor` reads `substrateDensity`.");
out.push("");
{
  const both = regionIds.filter((r) => Number.isFinite(Number(nanite[r]?.v)));
  const differ = both.filter((r) => Math.abs(Number(density[r]) - Number(nanite[r].v)) > 0.01);
  const gaps = differ.map((r) => ({ r, d: Math.abs(Number(density[r]) - Number(nanite[r].v)) })).sort((a, b) => b.d - a.d).slice(0, 4);
  out.push(`⚠️ **${differ.length} of ${both.length} regions carry a DIFFERENT nanite value from their lattice density.** The widest:`);
  out.push("");
  out.push("| region | lattice | nanite |");
  out.push("|---|---|---|");
  for (const g of gaps) out.push(`| ${regionName(g.r)} | ${f2(Number(density[g.r]))} | ${f2(Number(nanite[g.r].v))} |`);
  out.push("");
  out.push("⛑ **So the identical band produces an identical COUNT and a different WORLD** — which is the two-pairs cosmology working as authored, not two sources doing one job.");
}
out.push("");
out.push("## THE STARVED LIST — a tradition with no region inside its band is one nobody can play well anywhere");
out.push("");
{
  // ⛔ PER TRADITION, NOT PER SOURCE. `bandFor(tradition, model)` reads `substrateBand[tradition]` — the
  // map the engine itself calls — so this answers the question §3 actually asks. A per-source count
  // cannot: several traditions ride one source and they do not share a band.
  const densities = Object.values(density).map(Number).filter(Number.isFinite);
  const trads = Object.keys(C.traditionIndex?.byId || {}).map((t) => {
    const b = bandFor(t, sm);
    if (!b) return { t, b: null, inside: null };
    return { t, b, inside: densities.filter((v) => v >= b.center - b.width && v <= b.center + b.width).length };
  });
  const banded = trads.filter((x) => x.b);
  const starved = banded.filter((x) => x.inside === 0);
  const noBand = trads.filter((x) => !x.b);
  if (starved.length) {
    out.push(`⛔ **${starved.length} tradition(s) have NO region inside their band:** \`${starved.map((x) => x.t).join("`, `")}\`.`);
  } else {
    const thin = banded.slice().sort((a, b) => a.inside - b.inside).slice(0, 4);
    out.push(`✅ **None — every one of the ${banded.length} banded traditions has somewhere to work.** ⚠️ The thinnest four:`);
    out.push("");
    out.push("| tradition | band | regions inside |");
    out.push("|---|---|---|");
    for (const x of thin) out.push(`| \`${x.t}\` | ${f2(x.b.center - x.b.width)}–${f2(x.b.center + x.b.width)} | **${x.inside} of ${densities.length}** |`);
  }
  if (noBand.length) {
    out.push("");
    out.push(`⚠️ **And ${noBand.length} tradition(s) carry NO band at all** — \`${noBand.map((x) => x.t).join("`, `")}\` — so ground does not move them either way. ⬜ That is a statement about what they ARE, and worth confirming rather than assuming.`);
  }
}
out.push("");
out.push("## PER REGION — density, and what peaks there");
out.push("");
out.push("| region | density | nanite | strongest sources here |");
out.push("|---|---|---|---|");
for (const rid of regionIds) {
  const scored = perSource.map((s) => {
    const v = fieldValue(s.name, s.src, rid);
    if (v == null) return null;
    const f = s.band ? bandFactor(s.band, v) : (s.src?.floor ? 1 : null);
    return f == null ? null : { name: s.name, f };
  }).filter(Boolean).sort((a, b) => b.f - a.f);
  const top = scored.filter((x) => x.f >= 0.9).map((x) => `\`${x.name}\``).join(" · ") || `*(best: \`${scored[0]?.name}\` ${f2(scored[0]?.f)})*`;
  const nv = Number(nanite[rid]?.v);
  out.push(`| ${regionName(rid)} | ${f2(Number(density[rid]))} | ${Number.isFinite(nv) ? f2(nv) : "—"} | ${top} |`);
}
out.push("");
out.push(END);
const block = out.join("\n");

if (MD) { console.log(block); process.exit(0); }
const doc = readFileSync(DOC, "utf8");
const eol = doc.includes("\r\n") ? "\r\n" : "\n";
const i = doc.indexOf(BEGIN), j = doc.indexOf(END);
if (i < 0 || j < 0) { console.error("⛔ markers not found in docs/SUBSTRATE_ATLAS.md"); process.exit(1); }
const current = doc.slice(i, j + END.length).replace(/\r\n/g, "\n");
if (current === block) { console.log("substrate_atlas: identical to the file on disk"); process.exit(0); }
if (CHECK) { console.error("⛔ docs/SUBSTRATE_ATLAS.md is STALE — regenerate with `node scripts/substrate_atlas.mjs --write`"); process.exit(1); }
if (WRITE) {
  writeFileSync(DOC, doc.slice(0, i) + block.split("\n").join(eol) + doc.slice(j + END.length));
  console.log("substrate_atlas: docs/SUBSTRATE_ATLAS.md updated");
} else {
  console.log("DRY RUN — nothing written. Pass --write to apply.");
  console.log(`  lines: ${current.split("\n").length} on disk → ${block.split("\n").length} generated.`);
}
